### ISSUE TITLE
How to find the data

### ISSUE THREAD

**Issue by omarfahmy** [AryaAftab/ML-to-Predict-EE#1]
Dear Arya Aftab,
i am very interested in your code and your paper.. However, i don't find the dataset or trained weights to run the code....
Could you help me how to download the dataset and the initial weights...

Thanks & Best Regards
Omar

**Comment by AryaAftab** [comment]
Dear Omar Fahmy,
Thank you for showing your interest
Unfortunately, due to the use of the prepared dataset in future research, we are unable to publish it. You can prepare your dataset according to the portal mentioned in the article and easily use the prepared framework.

Best Regards
Arya Aftab

**Comment by omarfahmy** [comment]
Dear Arya,
thank you for your response... I am still unable to find the data.... Could you help me how to extract the data CSV file?...

**Comment by AryaAftab** [comment]
Research reports from 2010 onwards were **manually** extracted from the Web of Science search database with the niosome and thin-film hy­dration keywords. The keywords were searched in the report abstracts’ fields, where 94 reports were found at the end.
Factors involved in the synthesis of niosome that can affect drug entrapment efficiency include molecular weight of the drug, LogP of the drug, solubility in water of the drug, pKa strong acid of the drug, hy­dration media amount, solvent amount, HLB of the surfactant, drug/lipid molar ratio, chol/surf molar ratio, time of hydration, and temp of hydration. These factors were taken as inputs, while drug entrapment efficiency was the output of the models.
Finally, the reports with missing values were removed from the collection of reports. The final collection of data includes 66 samples and 13 reports.

**Comment by omarfahmy** [comment]
Ok thank you for your help dear Arya..

**Comment by AryaAftab** [comment]
You're welcome
